"""Render the check-to-requirement mapping as Markdown (docs/check-mapping.md).

The mapping is an interpretation made by people, so it is published in a form a
reviewer can read without opening the code. tests/test_catalog.py fails if the
committed document no longer matches the checks.
"""

from pathlib import Path

from nis2scan.catalog import load_requirements
from nis2scan.registry import CHECKS, load_all

HEADER = """\
# Check-to-requirement mapping

Generated by `nis2scan checks --markdown > docs/check-mapping.md`; do not edit by hand.

**Review:** reviewed and approved by OG V on 2026-09-25 (31 links). The two links of
CHK-BAK-002, added later, were reviewed and approved by OG V on 2026-09-26. Any later
change to a check's requirements needs a new review, recorded here.

Each link says that a check provides evidence for part of a legal requirement. Linking a
check to a requirement is an interpretation, so every link is marked `partial`: no single
technical check can show that a whole legal obligation is met. The reason for each link
is noted next to it in `src/nis2scan/checks/`.

Deliberately not linked:

- **CHK-SSH-003 to CIR 11.6.2(d).** MaxAuthTries drops a connection after failed attempts
  but does not block the user, which is what 11.6.2(d) requires.
- **TLS and incident-response-plan checks to CIR points.** The matching provisions (9.1,
  3.5) have not been extracted yet, so these checks map to the NIS2 articles only.
"""


def _short(text: str, limit: int = 110) -> str:
    text = " ".join(text.split())
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def render_markdown(catalog: Path) -> str:
    load_all()
    reqs = {r.id: r for r in load_requirements(catalog)}
    lines = [HEADER]
    for chk in sorted(CHECKS.values(), key=lambda c: c.meta.id):
        m = chk.meta
        lines.append(f"## {m.id}: {m.title}\n")
        lines.append(
            f"Severity **{m.severity.value}** ({m.severity_rationale}) · "
            f"coverage {m.coverage.value}\n"
        )
        lines.append("| Requirement | Provision | Legal text |")
        lines.append("|---|---|---|")
        for req_id in m.requirements:
            r = reqs.get(req_id)
            if r is None:
                lines.append(f"| `{req_id}` | *not in the reviewed catalog* | |")
                continue
            instrument = "NIS2" if r.source.instrument.startswith("Directive") else "CIR 2024/2690"
            lines.append(
                f"| `{req_id}` | {instrument}, {r.source.provision} | “{_short(r.source.quote)}” |"
            )
        lines.append("")
    return "\n".join(lines)
