# Weak: plaintext HTTP served without redirect, legacy TLS versions and ciphers,
# version disclosure, no HSTS.
events {}
http {
    server_tokens on;

    server {
        listen 80;
        root /usr/share/nginx/html;
    }

    server {
        listen 443 ssl;
        root /usr/share/nginx/html;
        ssl_certificate     /certs/server.crt;
        ssl_certificate_key /certs/server.key;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers   ALL:@SECLEVEL=0;
    }
}
